/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package festexample2;

import java.util.Date;

/**
 * Diálogo de altas
 * @author pablo
 */
public class AltaDialog extends java.awt.Dialog {

    //Referencia a la clase que maneja nuestro listado de vehículos. La recibimos
    //del frame principal
    private Metodos metodos;
    /**
     * Creates new form AltaDialog
     */
    public AltaDialog(java.awt.Frame parent, boolean modal, Metodos metodos) {
        super(parent, modal);
        initComponents();
        this.metodos = metodos;
        //Por defecto, el panel con los datos del camión no es visible
        panelCamion.setVisible(false);
        //Código necesario para centrar el diálogo en pantalla
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelPropietario = new javax.swing.JPanel();
        labelNombre = new javax.swing.JLabel();
        labelApellidos = new javax.swing.JLabel();
        editNombre = new javax.swing.JTextField();
        editApellidos = new javax.swing.JTextField();
        labelDni = new javax.swing.JLabel();
        editDni = new javax.swing.JTextField();
        editTelefono = new javax.swing.JTextField();
        labelTelefono = new javax.swing.JLabel();
        panelVehiculo = new javax.swing.JPanel();
        labelFecha = new javax.swing.JLabel();
        spinnerFecha = new javax.swing.JSpinner();
        labelModelo = new javax.swing.JLabel();
        labelMatricula = new javax.swing.JLabel();
        editModelo = new javax.swing.JTextField();
        editMatricula = new javax.swing.JTextField();
        comboTipo = new javax.swing.JComboBox();
        labelTipo = new javax.swing.JLabel();
        panelCamion = new javax.swing.JPanel();
        labelLongitud = new javax.swing.JLabel();
        checkPeligrosas = new javax.swing.JCheckBox();
        editLongitud = new javax.swing.JTextField();
        botonCancelar = new javax.swing.JButton();
        botonAceptar = new javax.swing.JButton();

        setName("altaDialog"); // NOI18N
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                closeDialog(evt);
            }
        });

        panelPropietario.setBorder(javax.swing.BorderFactory.createTitledBorder("Propietario"));

        labelNombre.setText("Nombre:");
        labelNombre.setToolTipText("Etiqueta nombre");

        labelApellidos.setText("Apellidos:");
        labelApellidos.setToolTipText("Etiqueta apellidos");

        editNombre.setToolTipText("Introduzca el nombre");
        editNombre.setName("editNombre"); // NOI18N

        editApellidos.setToolTipText("Introduzca los apellidos");
        editApellidos.setName("editApellidos"); // NOI18N

        labelDni.setText("DNI:");
        labelDni.setToolTipText("Etiqueta DNI");

        editDni.setToolTipText("Introduzca el DNI");
        editDni.setName("editDni"); // NOI18N

        editTelefono.setToolTipText("Introduzca el teléfono de contacto");
        editTelefono.setName("editTelefono"); // NOI18N

        labelTelefono.setText("Teléfono:");
        labelTelefono.setToolTipText("Etiqueta teléfono");

        javax.swing.GroupLayout panelPropietarioLayout = new javax.swing.GroupLayout(panelPropietario);
        panelPropietario.setLayout(panelPropietarioLayout);
        panelPropietarioLayout.setHorizontalGroup(
            panelPropietarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPropietarioLayout.createSequentialGroup()
                .addGroup(panelPropietarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelNombre)
                    .addComponent(labelApellidos)
                    .addComponent(labelDni)
                    .addComponent(labelTelefono))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelPropietarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(editNombre, javax.swing.GroupLayout.DEFAULT_SIZE, 322, Short.MAX_VALUE)
                    .addComponent(editApellidos)
                    .addComponent(editDni)
                    .addComponent(editTelefono)))
        );
        panelPropietarioLayout.setVerticalGroup(
            panelPropietarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPropietarioLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelPropietarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelNombre)
                    .addComponent(editNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelPropietarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelApellidos)
                    .addComponent(editApellidos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelPropietarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelDni)
                    .addComponent(editDni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelPropietarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(editTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelTelefono))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelVehiculo.setBorder(javax.swing.BorderFactory.createTitledBorder("Vehículo"));

        labelFecha.setText("Fecha:");

        spinnerFecha.setModel(new javax.swing.SpinnerDateModel(new java.util.Date(), null, null, java.util.Calendar.DAY_OF_WEEK));
        spinnerFecha.setToolTipText("Introduzca la fecha");
        spinnerFecha.setName("editFecha"); // NOI18N

        labelModelo.setText("Modelo:");
        labelModelo.setToolTipText("Etiqueta modelo");

        labelMatricula.setText("Matrícula:");
        labelMatricula.setToolTipText("Etiqueta matrícula");

        editModelo.setToolTipText("Introduzca el modelo");
        editModelo.setName("editModelo"); // NOI18N

        editMatricula.setToolTipText("Introduzca la matrícula");
        editMatricula.setName("editMatricula"); // NOI18N

        comboTipo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Coche", "Furgoneta", "Camión" }));
        comboTipo.setToolTipText("Introduzca el tipo de vehículo");
        comboTipo.setName("comboTipo"); // NOI18N
        comboTipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboTipoActionPerformed(evt);
            }
        });

        labelTipo.setText("Tipo:");
        labelTipo.setToolTipText("Etiqueta tipo");

        panelCamion.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos del camión"));

        labelLongitud.setText("Longitud:");
        labelLongitud.setToolTipText("Etiqueta longitud camión");

        checkPeligrosas.setText("Mercancías peligrosas");
        checkPeligrosas.setName("checkPeligrosas"); // NOI18N

        editLongitud.setToolTipText("Longitud del camión");
        editLongitud.setName("editLongitud"); // NOI18N

        javax.swing.GroupLayout panelCamionLayout = new javax.swing.GroupLayout(panelCamion);
        panelCamion.setLayout(panelCamionLayout);
        panelCamionLayout.setHorizontalGroup(
            panelCamionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCamionLayout.createSequentialGroup()
                .addComponent(labelLongitud)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(editLongitud, javax.swing.GroupLayout.DEFAULT_SIZE, 116, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(checkPeligrosas)
                .addGap(24, 24, 24))
        );
        panelCamionLayout.setVerticalGroup(
            panelCamionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCamionLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelCamionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelLongitud, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(checkPeligrosas)
                    .addComponent(editLongitud, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        javax.swing.GroupLayout panelVehiculoLayout = new javax.swing.GroupLayout(panelVehiculo);
        panelVehiculo.setLayout(panelVehiculoLayout);
        panelVehiculoLayout.setHorizontalGroup(
            panelVehiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelCamion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(panelVehiculoLayout.createSequentialGroup()
                .addGroup(panelVehiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelModelo)
                    .addComponent(labelMatricula)
                    .addComponent(labelTipo)
                    .addComponent(labelFecha))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelVehiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(spinnerFecha)
                    .addComponent(editMatricula)
                    .addComponent(comboTipo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(editModelo, javax.swing.GroupLayout.Alignment.TRAILING)))
        );
        panelVehiculoLayout.setVerticalGroup(
            panelVehiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelVehiculoLayout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addGroup(panelVehiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelFecha)
                    .addComponent(spinnerFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelVehiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelModelo)
                    .addComponent(editModelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelVehiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(editMatricula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelMatricula))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelVehiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comboTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelTipo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelCamion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        botonCancelar.setText("Cancelar");
        botonCancelar.setToolTipText("Pulse para cancelar");
        botonCancelar.setName("botonCancelar"); // NOI18N
        botonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCancelarActionPerformed(evt);
            }
        });

        botonAceptar.setText("Aceptar");
        botonAceptar.setToolTipText("Pulse para aceptar");
        botonAceptar.setName("botonAceptar"); // NOI18N
        botonAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAceptarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelPropietario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(panelVehiculo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(botonCancelar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(botonAceptar))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelPropietario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addComponent(panelVehiculo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonCancelar)
                    .addComponent(botonAceptar)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Closes the dialog
     */
    private void closeDialog(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_closeDialog
        setVisible(false);
        dispose();
    }//GEN-LAST:event_closeDialog

    private void comboTipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboTipoActionPerformed
        //Si la opción seleccionada es la dos (camión), mostramos el panel
        if (comboTipo.getSelectedIndex()==2)
            panelCamion.setVisible(true);
        else
            panelCamion.setVisible(false);
    }//GEN-LAST:event_comboTipoActionPerformed

    private void botonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCancelarActionPerformed
        //Cerramos el diálogo y volvemos a la pantalla original
        this.closeDialog(null);
    }//GEN-LAST:event_botonCancelarActionPerformed

    private void botonAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAceptarActionPerformed
        //Recogemos los datos de los componentes
        
        Vehiculo vehiculo = new Vehiculo();
        //Datos del propietario
        vehiculo.setNombrePropietario(editNombre.getText());
        vehiculo.setApellidosPropietario(editApellidos.getText());
        vehiculo.setDniPropietario(editDni.getText());
        vehiculo.setTelefonoPropietario(editTelefono.getText());
        
        //Datos del vehículo
        vehiculo.setFechaEntrada((Date)spinnerFecha.getModel().getValue());
        vehiculo.setModelo(editModelo.getText());
        vehiculo.setMatricula(editMatricula.getText());
        vehiculo.setTipoVehiculo(comboTipo.getSelectedItem().toString());
        if (comboTipo.getSelectedIndex()==2)
        {
            vehiculo.setMercanciasPeligrosas(checkPeligrosas.isSelected());
            vehiculo.setLongitud(Integer.parseInt(editLongitud.getText()));
        }
        
        metodos.addVehiculo(vehiculo);
        ((Principal)getParent()).refrescarTabla();
        this.closeDialog(null);
    }//GEN-LAST:event_botonAceptarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonAceptar;
    private javax.swing.JButton botonCancelar;
    private javax.swing.JCheckBox checkPeligrosas;
    private javax.swing.JComboBox comboTipo;
    private javax.swing.JTextField editApellidos;
    private javax.swing.JTextField editDni;
    private javax.swing.JTextField editLongitud;
    private javax.swing.JTextField editMatricula;
    private javax.swing.JTextField editModelo;
    private javax.swing.JTextField editNombre;
    private javax.swing.JTextField editTelefono;
    private javax.swing.JLabel labelApellidos;
    private javax.swing.JLabel labelDni;
    private javax.swing.JLabel labelFecha;
    private javax.swing.JLabel labelLongitud;
    private javax.swing.JLabel labelMatricula;
    private javax.swing.JLabel labelModelo;
    private javax.swing.JLabel labelNombre;
    private javax.swing.JLabel labelTelefono;
    private javax.swing.JLabel labelTipo;
    private javax.swing.JPanel panelCamion;
    private javax.swing.JPanel panelPropietario;
    private javax.swing.JPanel panelVehiculo;
    private javax.swing.JSpinner spinnerFecha;
    // End of variables declaration//GEN-END:variables
}
