/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package festexample2;

import javax.swing.table.DefaultTableModel;

/**
 *
 * @author pablo
 */
public class Principal extends javax.swing.JFrame {

    //Clase que encapsula la lista de vehículos
    private Metodos metodos = new Metodos();
    
    
    public Principal() {
        //Llamada a la función que genera Netbeans para inicializar todos los
        //componentes gráficos
        initComponents();
        refrescarTabla();
        //Código necesario para centrar el frame en pantalla
        setLocationRelativeTo(null);
    }
    
    /**
     * Este método se encarga de repintar la tabla. Para ello debemos construir
     * un modelo (el más sencillo es DefaultTableModel) y decirle que columnas
     * y que filas tiene.
     */
    public void refrescarTabla()
    {
        //Textos para las columnas
        String[] columnas = {"Matrícula","Modelo","Fecha"};
        //Creamos el modelo, indicando que ninguna de las columnas de la tabla
        //va a ser editable directamente
        DefaultTableModel defaultTableModel = new DefaultTableModel(columnas,0)
        {
            @Override
            public boolean isCellEditable(int row, int column) 
            {
               return false;
            }
        };
        
        //Añadimos las filas
        for (Vehiculo vehiculo : metodos.getListaVehiculos())
            defaultTableModel.addRow(vehiculo.getTableRepresentation());
        
        //Indicamos a la tabla cual es su modelo
        tablaVehiculos.setModel(defaultTableModel);
        //tablaVehiculos.setShowVerticalLines(true);
    }
        
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonNuevo = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaVehiculos = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Gestión de vehículos");

        buttonNuevo.setText("Nuevo vehículo");
        buttonNuevo.setToolTipText("Pulse aquí para introducir un nuevo vehículo");
        buttonNuevo.setName("buttonNuevo"); // NOI18N
        buttonNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonNuevoActionPerformed(evt);
            }
        });

        tablaVehiculos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tablaVehiculos.setName("tablaVehiculos"); // NOI18N
        jScrollPane1.setViewportView(tablaVehiculos);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(buttonNuevo)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 167, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonNuevo))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonNuevoActionPerformed
        //Creamos el diálogo y le pasamos una instancia de la clase métodos para
        //que el diálogo pueda dar de alta un nuevo vehículo.
        //El segundo parámetro a "true" indica que el diálogo va a ser modal
        AltaDialog altaDialog = new AltaDialog(this, true, metodos);
        altaDialog.setVisible(true);
    }//GEN-LAST:event_buttonNuevoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonNuevo;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablaVehiculos;
    // End of variables declaration//GEN-END:variables
}
